#!/bin/bash

db_name=$1

dropdb --if-exists --interactive $db_name
createdb $db_name
psql -c 'create extension postgis' $db_name

# All permit data
# schema=$(head -n 25  ${data_file} | csvsql -i postgresql --no-constraints --table $table_name)
# psql -c "$schema" $db_name
#
# cat $data_file | psql -c "copy ${table_name} from stdin with csv header delimiter ',' NULL E'' quote '\"'" $db_name
#
# psql -c "alter table ${table_name} add column geom geometry(Point, ${oregon_north_srs})" $db_name
# psql -c "update ${table_name} set geom = ST_SetSRID(ST_MakePoint(x,y), ${oregon_north_srs})" $db_name
# psql -c "create index geom_idx ON ${table_name} using gist(geom)" $db_name
# psql -c "alter table ${table_name} alter column geom type geometry(Point, 4326) using st_transform(geom, 4326)" $db_name

shp2pgsql -t 2D -I -D data/shp/neighborhoods.shp | psql $db_name
shp2pgsql -t 2D -I -D data/shp/residential-permits.shp residential_permits | psql $db_name
